packages:
  - apps/*
  - packages/*
  - workers/*

allowBuilds:
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - miniflare@5.20260826.0-alpha
  - wrangler@4.127.0

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

patchedDependencies:
  '@atproto-labs/fetch@0.3.5': patches/@atproto-labs__fetch@0.3.5.patch
  '@lynx-js/web-core@0.25.0': patches/@lynx-js__web-core@0.25.0.patch
